
package de.codecentric.namespace.weatherservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WeatherException", targetNamespace = "http://www.codecentric.de/namespace/weatherservice/exception")
public class WeatherException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private de.codecentric.namespace.weatherservice.exception.WeatherException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WeatherException(String message, de.codecentric.namespace.weatherservice.exception.WeatherException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WeatherException(String message, de.codecentric.namespace.weatherservice.exception.WeatherException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.codecentric.namespace.weatherservice.exception.WeatherException
     */
    public de.codecentric.namespace.weatherservice.exception.WeatherException getFaultInfo() {
        return faultInfo;
    }

}
