
package de.codecentric.namespace.weatherservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import de.codecentric.namespace.weatherservice.general.ForecastRequest;
import de.codecentric.namespace.weatherservice.general.ForecastReturn;
import de.codecentric.namespace.weatherservice.general.WeatherInformationReturn;
import de.codecentric.namespace.weatherservice.general.WeatherReturn;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 */
@WebService
public interface WeatherService {

    public WeatherInformationReturn getWeatherInformation(
            String zip)
            throws WeatherException
            ;

    public ForecastReturn getCityForecastByZIP(
            ForecastRequest forecastRequest)
            throws WeatherException
            ;

    public WeatherReturn getCityWeatherByZIP(
            ForecastRequest forecastRequest)
            throws WeatherException
            ;

}
